logging:
  level:
    org:
      springframework:
        #security: DEBUG
      hibernate:
        #type: TRACE

      
server:
  #forward-headers-strategy: NATIVE
  #tomcat:
    #remoteip:      #remote-ip-header: X-FORWARDED-FOR
      #protocol-header: X-FORWARDED-PROTO
  #address: 192.168.x.x
  port: ${PORT:8440}
  ssl:
    key-store: classpath:test.p12
    key-store-password: test123
    key-store-type: pkcs12
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
  servlet:
    #context-path: /PRO2112_Final
    session:
      cookie:
        http-only: true
        #secure: false
        #max-age: 2592000 #Cookies expire after 30 days
      tracking-modes: cookie
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: 'PaulnguyenFlorida2017'
    url: jdbc:sqlserver://sql.freeasphost.net\MSSQL2016;databaseName=tdanh2k_phpTest
    username: tdanh2k
    #hikari:
      #connection-timeout: 7000
  jpa:
    hibernate:
      #naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    encoding: UTF-8
    enable-spring-el-compiler: true
  #mvc:
    #servlet:
      #path: /PRO2112_Final
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: "danhntps09651@fpt.edu.vn"
    
    properties:
      mail:
        smtp:
          ssl:
            enable: "true"
          sasl:
            enable: "true"
            mechanisms : "XOAUTH2"
          auth:
            login:
              disable: "true"
            plain:
              disable: "true"
      
security:
  require-ssl: false
